---
- name: Create group
  group:
    name: prometheus
    state: present

- name: Create user
  user:
    name: prometheus
    group: prometheus
    shell: /sbin/nologin
    create_home: false

- name: Copy binary file
  copy:
    src: node_exporter
    dest: /usr/bin
    owner: prometheus
    group: prometheus
    mode: '0770'

- name: Copy service config file
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system

- name: Reload systemd daemon, enable and start node exporter service
  service:
    name: node_exporter
    enabled: true
    state: started
    daemon_reload: true
