- name: Terst playbook
  hosts: prometheus_server
  become: yes

  tasks:
    - name: Create dirs
      file:
        path: '{{ item }}'
        state: directory
        owner: test
        group: test
      loop:
        - /etc/bla1
        - /etc/bla2
      delegate_to: 127.0.0.1
